### ISSUE TITLE
Wrapped errors wrongly apply formatting

### ISSUE THREAD

**Issue by pi0** [nuxt-contrib/consola#109]
Using using `wrap*` helpers, we implicitly assume first argument as consola logObj format which might end with formatting errors. (https://github.com/nuxt/nuxt.js/issues/8741)

### Reproduction

```js
const consola = require('consola')

const error = new Error('boom')
const errorObj = {
  date: new Date().toISOString(),
  level: 'error',
  message: error.message,
  error: { stack: error.stack, message: error.message }
}

console.log(errorObj)
consola.wrapAll()
console.log(errorObj)
```

### Workarounds

1. Use different field name than message, error
2. `console.log(JSON.stringify(errorObj, null, 2))`
3. `console.log('', errorObj)`
4. `consola.restoreAll()`

**Comment by gkatsanos** [comment]
unfortunately workarounds dont work for us as Datadog doesnt see the ouput as valid JSON. 
Would restoreAll() be a better option?

**Comment by gkatsanos** [comment]
can I over-write the built in reports of nuxt core with a setting in the nuxt.config.js ?

**Comment by pi0** [comment]
@gkatsanos You can set consola reporters in body of `nuxt.config` file. 

Also respectfully, please use channels like nuxt discord to get help for your solutions such as datadog integration. I would also be more than happy even if can help. Sending random questions in several repo/issues is wasting time.

**Comment by gkatsanos** [comment]
Respectfully, I am a bit disappointed about the documentation and the bugs discovered often in Nuxt. (I think already 3 for me). 
Take for example Consola and the documentation : There's no mention that all SSR logs are wrapped and transformed with `consola`.  How is one supposed to know? 
I understand this is community-driven voluntary-work OSS , and I appreciate the help provided. I would be asking in Discord channels but contrarily to the Reactiflux communities unfortunately the Vue one is notably silent. There's a lot of questions and not a lot of answers.

**Comment by pi0** [comment]
Issue fixed in [v2.15.1](https://github.com/nuxt-contrib/consola/releases/tag/v2.15.1)

@gkatsanos You can get update with `yarn upgrade nuxt` (or better recreating lock file)

**Comment by gkatsanos** [comment]
@pi0 I think I need to wait until its propagated to the main repo, right? https://github.com/nuxt/nuxt.js/releases

**Comment by pi0** [comment]
@gkatsanos nop  npm magic! (nuxt has range dependency on consola like `^2.15.0`) when lock file is created, it will fetch latest possible in range :)

**Comment by gkatsanos** [comment]
@pi0 would you be available on the Vue Discord ? ( console.error ( { .. } ) still generates invalid JSON)

**Comment by pi0** [comment]
@gkatsanos Sure pi0#6582

**Comment by gkatsanos** [comment]
console.error when wrapped still adds ERROR in front of the object returned. reproduction: https://repl.it/@gkatsans/Consola-2#index.js 
I guess this may be intended, in which case what would be the workaround?

**Comment by pi0** [comment]
It is intended indeed. Fancy reporter adds the badge.

**Comment by gkatsanos** [comment]
Thanks. I can add a parser in Datadog that handles it but I guess going with the previous suggestion of 
```js

consola.setReporters([
  {
    log: (e) => {
      process.stdout.write(JSON.stringify(e))
    },
  },
])

```
in nuxt.config.js seems a more safe solution as I could also do further manipulation there centrally.. What do you think? (add a timestamp, structure the response etc)

**Comment by pi0** [comment]
nuxt.config is safest place indeed (also please note consola should not be modified in other places. only use console.* calls)
