### ISSUE TITLE
hide info messages

### ISSUE THREAD

**Issue by deni5n** [nuxt-contrib/consola#112]
I tried to find in the documentation how to configure Consola for production, but I couldn't. Tell me how to turn off the Consola for production and leave it for development and tests?

something like 
```
production: true 
```
in instance settings 

As a result, when node_env is not production logs will not be displayed.Or is there no such setting and you need to make your own wrapper?

**Comment by pi0** [comment]
Hi @deni5n. Is your intended behavior to _hide_ all console/consola logs in prod?

**Comment by deni5n** [comment]
yes

**Comment by pi0** [comment]
You can set `CONSOLA_LEVEL=1` environment variable to only show warn and error.  List of all levels: https://github.com/nuxt-contrib/consola/blob/master/src/logLevels.js

**Comment by deni5n** [comment]
Awesome! thank you very much!

**Comment by gkatsanos** [comment]
@pi0  would using `CONSOLA_LEVEL` also work if I log via console.log using this structure: 
```
{
  time: '2022-02-11T16:09:55.088Z',
  level: 'WARN',
  http: {
    url: '/suppliers/333333333333/recommendations/products',
    baseUrl: 'https://explore-backend.internal.wlw-1.staging.visable.cloud/explore_backend',
    status_code: 400,
    method: 'get',
    useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36'
  },
  message: 'Request failed with status code 400',
  dd: {
    trace_id: '1808205333969640922',
    span_id: '1808205333969640922',
    service: 'visable/company_profile/frontend',
    version: '2.15.8'
  }
}
```
